### ISSUE TITLE
elitetorrent: not working in python 3.8

### ISSUE THREAD

**Issue by ngosang** [iordic/qbittorrent-search-plugins#1]
```
[nova3]$ python3 nova2.py elitetorrent all tiempo
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "nova2.py", line 136, in run_search
    engine.search(what, cat)
  File "/home/kizar/Downloads/qbit/data/qBittorrent/nova3/engines/elitetorrent.py", line 56, in search
    links = links + items
TypeError: unsupported operand type(s) for +: 'set' and 'list'
"""
```

**Comment by iordic** [comment]
Apparently working now 891d7144fbd5798baf9aac9e73a11d3f6044f177

**Comment by ngosang** [comment]
Thanks!
